apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-pipeline
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/TaiHuynh31/sampleArgoCD.git'
    path: '.'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeflow
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

