apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-pipeline
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/TaiHuynh31/sampleArgoCD.git'  # Replace with your Git repository URL
    path: '.'                                                  # Replace with the correct path to your app configuration
    targetRevision: HEAD                                       # Specify the branch or commit
  destination:
    server: 'https://kubernetes.default.svc'                  # Kubernetes API server
    namespace: kubeflow                                        # Namespace to deploy
  project: default                                             # ArgoCD project name
  syncPolicy:
    automated:
      prune: true                                              # Automatically delete resources no longer in Git
      selfHeal: true                                           # Automatically sync out-of-sync resources
    syncOptions:
      - CreateNamespace=true                                   # Create namespace if not exists

---
apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-kubeflow-pipeline
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: PostSync                          # Lifecycle hook to trigger after sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded       # Delete Job after success
spec:
  template:
    spec:
      containers:
      - name: trigger-pipeline
        image: python:3.9
        command: ["python3", "-c"]
        args:
        - |
          import kfp
          client = kfp.Client() 
          client.create_run_from_pipeline_package(
              pipeline_file='https://github.com/TaiHuynh31/sampleArgoCD/raw/main/iris_pipeline.yaml',  
              arguments={}                                                                           
          )
      restartPolicy: Never
