apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io