apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-patch-role-binding
  namespace: kubeflow
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubeflow
roleRef:
  kind: Role
  name: pod-patch-role
  apiGroup: rbac.authorization.k8s.io