apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-pipeline
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/TaiHuynh31/sampleArgoCD.git'  # Replace with your Git repository URL
    path: '.'                                                  # Replace with the correct path to your app configuration
    targetRevision: HEAD                                       # Specify the branch or commit
  destination:
    server: 'https://kubernetes.default.svc'                  # Kubernetes API server
    namespace: kubeflow                                        # Namespace to deploy
  project: default                                             # ArgoCD project name
  syncPolicy:
    automated:
      prune: true                                              # Automatically delete resources no longer in Git
      selfHeal: true                                           # Automatically sync out-of-sync resources
    syncOptions:
      - CreateNamespace=true                                   # Create namespace if not exists
