apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: iris-pipeline-
spec:
  entrypoint: iris-pipeline
  templates:
    - name: iris-pipeline
      steps:
        - - name: preprocess
            template: preprocess-step

        - - name: train
            template: train-step
            dependencies:
              - preprocess

        - - name: evaluate
            template: evaluate-step
            dependencies:
              - train

    - name: preprocess-step
      container:
        image: "preprocess:local"
        command: ["python"]
        args: ["preprocess.py"]
        volumeMounts:
          - name: shared-data
            mountPath: /data

    - name: train-step
      container:
        image: "train:local"
        command: ["python"]
        args: ["train.py"]
        volumeMounts:
          - name: shared-data
            mountPath: /data
          - name: shared-model
            mountPath: /model

    - name: evaluate-step
      container:
        image: "evaluate:local"
        command: ["python"]
        args: ["evaluate.py"]
        volumeMounts:
          - name: shared-data
            mountPath: /data
          - name: shared-model
            mountPath: /model
          - name: shared-metrics
            mountPath: /metrics

  volumes:
    - name: shared-data
      emptyDir: {}
    - name: shared-model
      persistentVolumeClaim:
        claimName: model-pvc
    - name: shared-metrics
      emptyDir: {}
