# trigger-pipeline-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-kubeflow-pipeline
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: trigger-pipeline
        image: python:3.9
        command: ["sh", "-c"]
        args:
        - |
          pip install kfp &&                                   
          python3 -c "
          import kfp
          client = kfp.Client()  
          client.create_run_from_pipeline_package(
              pipeline_file='https://github.com/TaiHuynh31/sampleArgoCD/raw/main/iris_pipeline.yaml',  
              arguments={}                                                                           
          )"
      restartPolicy: Never