apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iris-pipeline
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/TaiHuynh31/sampleArgoCD.git'
    path: 'argo-workflows'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true